name: Docker Publish

on:
  release:
    types: [published]
  schedule:
    - cron: '0 0 * * *'

jobs:
  push_to_registries:
    name: Push Docker image to Docker Hub and GHCR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    env:
      # Dynamically compute IMAGE_NAME by removing the "docker-" prefix from the repo name
      IMAGE_NAME: ${{ replace((split(github.repository, '/'))[1], 'docker-', '') }}
    steps:
      - name: Set RELEASE_TAG environment variable
        run: |
          echo "Fetching latest release tag..."
          RELEASE_TAG=$(gh release list --limit 1 --json tagName -q '.[0].tagName')
          if [ -z "$RELEASE_TAG" ]; then
            echo "No release found. Exiting."
            exit 1
          fi
          echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_ENV
          echo "Using release tag: $RELEASE_TAG"

      - name: Check out the repo at the latest release tag
        uses: actions/checkout@v4
        with:
          ref: ${{ env.RELEASE_TAG }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            docker.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            ${{ env.RELEASE_TAG }}
            latest

      - name: Build and push Docker images
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation for Docker Hub
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: docker.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
          github-token: ${{ secrets.GH_TOKEN }}

      - name: Generate artifact attestation for GHCR
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
          github-token: ${{ secrets.GH_TOKEN }}
